### ISSUE TITLE
Typo in link protocol

### ISSUE THREAD

**Issue by illright** [HarrisJT/web-launch-checklist#1]
[This](https://github.com/HarrisJT/web-launch-checklist/blob/master/index.html#L70) link points to `hhttp://optimizilla.com/`, which is an invalid protocol

**Comment by HarrisJT** [comment]
Thanks! Fixed in https://github.com/HarrisJT/web-launch-checklist/commit/8e7e817c09c3a8a6b51f62e71e60147cc46d1a4b
