### ISSUE TITLE
Invalid SSL certificate on website

### ISSUE THREAD

**Issue by itsdevdom** [HarrisJT/web-launch-checklist#6]
It seems that the SSL certificat is invalid, which results in Chrome showing a security warning page the user has to accept. Tested on Chrome 68, Windows 10.

Also see:
![cert](https://user-images.githubusercontent.com/7271961/44492720-d4638600-a665-11e8-966e-bc77a7823113.PNG)

Plus, the security dev panel:
![snip](https://user-images.githubusercontent.com/7271961/44492764-f5c47200-a665-11e8-8982-df4e2063331f.PNG)

**Comment by HarrisJT** [comment]
Thank you for your report. I am almost ready with a new version of the website, so I am going to close this issue. I apologize for the long wait.
